management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spockboot?useSSL=false&serverTimezone=UTC
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis
      port: 6379

app:
  public-paths:
    - /api/**
    - /actuator/**
    - /h2-console/**
