management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d3kmo215pdvs73c3183g-a/spok_f3no
    username: spok_f3no_user
    password: Tg5DaXoLwh6R7moTcbCKt2smVv6yv5h9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: red-d2fh1jmr433s73bblha0
      port: 6379
#      ssl:
#        enabled: true

app:
  public-paths:
    - /api/**
    - /actuator/**
    - /h2-console/**
