spring:
  application:
    name: Booking Service
  profiles:
    active: ${PROFILE:local}

server:
  port: 8081

logging:
  level:
    root: ${LOG_LEVEL:info}
    org:
      springframework: INFO
  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

app:
  public-paths:
    - /api/**
  kafka-topic: seat_reservation
  seat-lock-ttl-seconds: 300

