management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d2fee36mcj7s73enqi40-a.oregon-postgres.render.com/spok
    username: spok_user
    password: VZih6lxGVwQsIfxU3O77PeqVXmuHDc1B
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: oregon-keyvalue.render.com
      port: 6379
      username: red-d2fh1jmr433s73bblha0
      password: UFRyBMbNMMekDXYzod5hENTNbrLiMseL
      ssl:
        enabled: true

app:
  public-paths:
    - /api/**
    - /actuator/**
    - /h2-console/**
