spring:
  application:
    name: Seats
  profiles:
    active: ${PROFILE:local}

  datasource:
    url: jdbc:postgresql://localhost:5432/spok
    username: usr
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

logging:
  level:
    root: ${LOG_LEVEL:info}
    org:
      springframework: INFO
  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

app:
  public-paths:
    - /api/**
  kafka-topic: seat_reservation
  seat-lock-ttl-seconds: 300

