spring:
  application:
    name: Seats
  profiles:
    active: ${PROFILE:local}
  datasource:
    url: jdbc:mysql://localhost:3306/spockboot?useSSL=false&serverTimezone=UTC
    username: root
    hikari:
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

logging:
  level:
    root: ${LOG_LEVEL:info}
    org:
      springframework: INFO
  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

app:
  public-paths:
    - /api/**
  kafka-topic: seat_reservation
  seat-lock-ttl-seconds: 300

