version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: spockboot
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
