management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spockboot?useSSL=false&serverTimezone=UTC

app:
  public-paths:
    - /api/auth/**
    - /api/register
    - /api/events
    - /api/venues
    - /actuator/**
    - /h2-console/**
