spring:
  application:
    name: QWeb
  profiles:
    active: ${PROFILE:local}
  datasource:
    url: jdbc:mysql://localhost:3306/spockboot?useSSL=false&serverTimezone=UTC
    username: root
    hikari:
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080

jwt:
  access_token:
    expiration: 600000
  refresh_token:
    expiration: 86400000
  secret: sMDFD8HXPKGjA5LwGck2iM0U8K0naKt1VEdLtMGkUz4=
  issuer: QWeb

logging:
  level:
    root: ${LOG_LEVEL:info}
    org:
      springframework: info
      hibernate.SQL: debug
      hibernate.orm.jdbc.bind: trace
      hibernate.type.descriptor.sql: trace

  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

app:
  public-paths:
    - /api/auth/**
    - /api/register
    - /api/events
    - /api/venues

