management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
#  mem:spockboot — creates an in-memory DB named spockboot.
#  DB_CLOSE_DELAY=-1 — keeps the DB alive for the app's entire lifecycle.
#  MODE=MySQL — excellent if you're switching between H2 and MySQL; it makes H2 behave more like MySQL (e.g., data types, syntax).
#  Using default sa user with no password is fine for local/dev.
  datasource:
    url: jdbc:h2:mem:spockboot;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
